### ISSUE TITLE
Call to undefined method Binarcode\LaravelMailator\Scheduler::init() 

### ISSUE THREAD

**Issue by maiskiykot** [BinarCode/laravel-mailator#2556]
Hi!
I tried use your package in my controller Task. I have error from title.

 Binarcode\LaravelMailator\Scheduler::init('Task reminder')
        ->mailable(new TaskReminderMailable())
         ->recipients('kot@mail.ru', 'ru@gmail.com')
         ->daily()
        ->weeks(1)
        ->before($expirationDate)
        ->save();

**Comment by maiskiykot** [comment]
Call to undefined function Binarcode\LaravelMailator\Models\fn()

**Comment by maiskiykot** [comment]
Many-many errors in code.

**Comment by binaryk** [comment]
Please ensure your `$expirationDate` is a `CarbonInterface` instance. And check your `mailable` instance. 

![image](https://user-images.githubusercontent.com/6833714/126897678-912388f1-93a1-4d02-8f73-b577982736fe.png)

Also, what is your package version?

**Comment by f00bar** [comment]
@binaryk I'm also getting this error. I'm on a project that's using php 7.4.3 so I'm using release 2.0 for this package. However, when I try to use it I get:

PHP Error:  Call to undefined method Binarcode\LaravelMailator\Scheduler::init() 

I really like this package and it will be great if I can use it in my project.

Thanks!
