### ISSUE TITLE
Delay in minutes is not working

### ISSUE THREAD

**Issue by dstollie** [BinarCode/laravel-mailator#2564]
I Think that there is a bug where delay_minute is not working properly

In `AfterConstraint.php`

The below code at the end diffs the hours between the delay_minutes. I think the diff should be done in minutes.

```php
        //till ends we should have at least toDays days
        return $schedule->isOnce()
            ? $schedule->timestamp_target->diffInHours(now()->floorSeconds()) === $schedule->delay_minutes
            : $schedule->timestamp_target->diffInHours(now()->floorSeconds()) > $schedule->delay_minutes;
```

After working some more with this package I think I discovered an additional issue; In the `AfterConstraint` the condition should always be `>=` instead of `>`. When you have an delay of 1 hour you expected i to sent after 1 hour instead of > 1 hour

r.48 AfterConstraint.php
```php
      : $schedule->timestamp_target->diffInHours(now()->floorSeconds()) > $schedule->delay_minutes;
```
Should be
```php
      : $schedule->timestamp_target->diffInMinutes(now()->floorSeconds()) >= $schedule->delay_minutes;
```

**Comment by dstollie** [comment]
It also looks like that the `unique()` method is not working as expected

The mailable "Modules\EnergySubmission\Mail\IncompleteSubmissionMissingMeterSerialMailable" does exists in my database and "%IncompleteSubmissionMissingMeterSerialMailable%" does give the expected results but the whole namespaces does not match.

Below code is what eventually is being added but does not work in our use case
```php
public function scopeMailableClass($query, $class)
{
    $query->where('mailable_class', 'LIKE', "%Modules\EnergySubmission\Mail\IncompleteSubmissionMissingMeterSerialMailable%");
}
```

**Comment by dstollie** [comment]
Additionaly after working more with this awesome package I think I found a bug in the `unique()` method functionality. It seems that it does not working as expected

There seems to be going something wrong on the like statement when a "\" is in the $class

This doesnt work
```php
    public function scopeMailableClass($query, $class)
    {
        $query->where('mailable_class', 'LIKE', "%Modules\EnergySubmission\Mail\IncompleteSubmissionMissingMeterSerialMailable%");
    }
```

This neither
```php
    public function scopeMailableClass($query, $class)
    {
        $query->where('mailable_class', 'LIKE', "%\IncompleteSubmissionMissingMeterSerialMailable%");
    }
```

This works
```php
  public function scopeMailableClass($query, $class)
  {
      $query->where('mailable_class', 'LIKE', "%IncompleteSubmissionMissingMeterSerialMailable%");
  }
```

This is a screeny from the contents
![Screenshot 2022-10-28 at 20 59 54](https://user-images.githubusercontent.com/7110155/198712341-4432800e-c36d-40ca-8a92-f55b732f2d16.png)

**Comment by dstollie** [comment]
Wip in this fork: https://github.com/zonneplan/laravel-mailator/commits/master

**Comment by binaryk** [comment]
Thanks @dstollie , any progress with that one?
