### ISSUE TITLE
Emails won't send (no errors given)

### ISSUE THREAD

**Issue by HeadStudios** [BinarCode/laravel-mailator#2572]
I have just setup the Kernel command and attempted to send an email from my Controller - running php artisan schedule:run completes the job successfully however no last_failed_at or last_sent_at columns are full. 

Below is Gist for controller code:
https://gist.github.com/HeadStudios/a6fbf11b54228904aba5f71af2153c9a

Below is Gist for MyMailGun Maileable:
https://gist.github.com/HeadStudios/eede6d6c3d1f36ad9df29d05cc64fbc6

Kernel:
https://gist.github.com/HeadStudios/2a589df95f10caf9da0009b7cd12891c

Below is video for context:
https://share.getcloudapp.com/Z4unZdmo

Thank you!

**Comment by HeadStudios** [comment]
Please ignore previous issue - I can confirm emails are being sent all though I am surprised at the behavior. I would have assumed if 5 emails are scheduled to be sent 1 minute after now then a php artisan schedule:run action after 4 minutes would send all 5 emails but it seems this is not the case. Any input you could give on this much appreciated but otherwise feel free to close this issue.

**Comment by HeadStudios** [comment]
Video for context: https://share.getcloudapp.com/12u7Og8A

Basically everything seems to be working fine and the emails are being added to the database table (mailator_schedulers) - however no email is being sent:
https://share.getcloudapp.com/12u7Og8A

I am in the process of investigating the "logic" of how this works - any input on the function that:
* Queries the table and selects the mail messages to send
* Executes the actual send

Would be appreciated.

**Comment by HeadStudios** [comment]
Looks like I'm on my own :(

**Comment by binaryk** [comment]
You simply have to make sure the schedule command is in the Kernel (https://github.com/BinarCode/laravel-mailator?tab=readme-ov-file#run). And make sure you have the cronjob enabled.
