### ISSUE TITLE
 public const MINUTES_IN_DAY = 60 * 60; Why is it like this?

### ISSUE THREAD

**Issue by capricorn05** [BinarCode/laravel-mailator#2574]
class ConverterEnum
{
    public const MINUTES_IN_HOUR = 60;
    public const MINUTES_IN_DAY = 60 * 60;
    public const MINUTES_IN_WEEK = 168 * 60;
    public const HOURS_IN_DAY = 24;
    public const HOURS_IN_WEEK = 168;
}

**Comment by binaryk** [comment]
Indeed it's a bug, but when converting back, it uses the same constant, so it doesn't create any problems.
