### ISSUE TITLE
In After Constraint,  minutes frequency not working.

### ISSUE THREAD

**Issue by encoderit-salman** [BinarCode/laravel-mailator#2575]
### Please review 

> AfterConstraint.php

`return $schedule->isOnce()
                    ? $schedule->timestamp_target->diffInHours(now()->floorSeconds()) === $schedule->delay_minutes
                    : $schedule->timestamp_target->diffInHours(now()->floorSeconds()) > $schedule->delay_minutes;`

**Should be like this**

`return $schedule->isOnce()
            ? $schedule->timestamp_target->diffInMinutes(now()) >= $schedule->delay_minutes && is_null($schedule->completed_at)
            : $schedule->timestamp_target->diffInMinutes(now()) > $schedule->delay_minutes;`
on line 46 to 48

**Comment by binaryk** [comment]
Fixed https://github.com/BinarCode/laravel-mailator/releases/tag/6.0.1

**Comment by frankmichel** [comment]
@binaryk It think it still needs to be fixed in line 55, see https://github.com/BinarCode/laravel-mailator/blob/6.2.0/src/Constraints/AfterConstraint.php and https://github.com/BinarCode/laravel-mailator/pull/2581
