### ISSUE TITLE
Delay for scheduled emails is being miscalculated

### ISSUE THREAD

**Issue by marko-b** [BinarCode/laravel-mailator#2582]
It appears that the delay for scheduled emails is being miscalculated due to an incorrect value of the `MINUTES_IN_DAY` constant.

`public const MINUTES_IN_DAY = 60 * 60;` should be `public const MINUTES_IN_DAY = 60 * 24;`
Located in `class ConverterEnum`

**Comment by binaryk** [comment]
Fixed https://github.com/BinarCode/laravel-mailator/releases/tag/6.0.1
